# Tratamento de Exceções
  ## Definição

  O tratamento de exceções é uma forma de tratar erros em tempo de execução. O tratamento de exceções é feito através de blocos try-catch. O bloco try é utilizado para colocar o código que pode gerar uma exceção. O bloco catch é utilizado para colocar o código que será executado caso uma exceção seja gerada. Exemplo:

    ```java
    try {
        int a = 10;
        int b = 0;
        int c = a / b;
    } catch (ArithmeticException e) {
        System.out.println("Erro: divisão por zero");
    }
    ```

  ## Exceções comuns
  ### Divisão por zero

        ```java
        int a = 10;
        int b = 0;
        int c = a / b;
        ```

  ### Conversão de tipos de dados inválidos

        ```java
        String s = "abc";
        int a = Integer.parseInt(s);
        ```

  ### Acessar uma posição inválida em um arranjo

        ```java
        int[] a = new int[10];
        int b = a[10];
        ```

   ### Acessar uma String nula

        ```java
        String s = null;
        int a = s.length();
        ```

  ## Bloco para capturar uma exceção 

    ```java
    try {
        int a = 10;
        int b = 0;
        int c = a / b;
    } catch (ArithmeticException e) {
        System.out.println("Erro: divisão por zero");
    }
    ```

  ## Bloco para capturar diferentes exceções 

    ```java
    try {
        int a = 10;
        int b = 0;
        int c = a / b;
    } catch (ArithmeticException e) {
        System.out.println("Erro: divisão por zero");
    } catch (Exception e) {
        System.out.println("Erro: " + e.getMessage());
    }
    ```

  ## Bloco finally

   O bloco finally é executado sempre, independente se uma exceção foi gerada ou não. Exemplo:

    ```java
    try {
        int a = 10;
        int b = 0;
        int c = a / b;
    } catch (ArithmeticException e) {
        System.out.println("Erro: divisão por zero");
    } finally {
        System.out.println("Fim do programa");
    }
    ```

  ## Lançar uma exceção

    ```java
    public static void main(String[] args) {
        try {
            int a = 10;
            int b = 0;
            if (b == 0) {
                throw new ArithmeticException("Divisão por zero");
            }
            int c = a / b;
        } catch (ArithmeticException e) {
            System.out.println("Erro: " + e.getMessage());
        }
    }
    ```
